baseurl:
url: https://qingwangchen.github.io/
title: Qingwang Chen
subtitle: "Infinity Beyond"
description: "Qingwang's personal page"
date_format: "ordinal"
# timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

author: qingwangchen
organization: School of Life Sciences, Fudan University
organization_url: https://life.fudan.edu.cn/
github_username: qingwangchen
location: Shanghai, China
email: qwchen20@fudan.com

# Navigation
navs:
  -
    href: /
    label: Homepage

  -
    href: /cv/
    label: CV

  -
    href: /publications/
    label: Publications

  -
    href: /categories/
    label: Blogs

  -
    href: /wiki/
    label: Wiki

  # -
  #   href: /links/
  #   label: Links

# RSS
subscribe_rss: /feed.xml

# Jekyll
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: qingwangchen/qingwangchen.github.io

# Search
simple_jekyll_search:
    fulltext: false # full text search enable
    limit: 10 # limitation of the search results to show

# Analytics
google:
    analytics_id: UA-80669434-1
github: [metadata]
